rm(list=ls())

####
#all
####

library(ggpubr)
library(tidyverse)

#Here, set the file name of the table generated by get_seq_lengths.py
sample.filename = "data/test_seq_lengths.txt"

#use their script to import to ensure correct ref lengths
sample.data = as.matrix(read.table(
  sample.filename,
  header = T,
  row.names = 1,
  sep = "\t"
))

#remove X from locus name
colnames(sample.data) <- gsub("X", "", colnames(sample.data))

#view data
#view(sample.data)

#set length of reference exon
reference.len = as.numeric(sample.data[1,])

#extract only sample exon lengths
sample.len = sample.data[2:length(sample.data[, 1]),]

#calculate percentage of exon recovered for each exon in each individual
percent.len = sweep(sample.len, 2, reference.len, "/")
percent.len = ifelse(percent.len > 1, 1, percent.len)

####
#uncomment to ID low data samples
####
percent.len.low = ifelse(percent.len > 0.01, 1, percent.len)
percent.len.low_df<-data.frame(sort(rowSums(percent.len.low)))
view(percent.len.low_df)

###
# taxonomic scale
###

#read in taxonomy dataset
tn<-read.csv("data/sample_data - samples_for_phylo.csv")

#only Myristicaceae samples
tn<-tn[tn$Family=="Myristicaceae",]
percent.len.myr<-percent.len[rownames(percent.len)%in%tn$Namelist,]

#check names
rownames(percent.len.myr)
as.numeric(percent.len.myr)


#set thresholds
limits <- c(0.25, 0.5, 0.75,0.9)

#make empty matrix
exon_stats <- matrix(nrow = length(limits), ncol = length(limits))

#loop through threshold combinations
for (i in 1:length(limits)) {
  for (j in 1:length(limits)) {
    percent.len.limit <- percent.len.myr

    # e.g. if percentage exon length recovered is >= 75% make value 1
    # if not make value 0
    percent.len.limit[percent.len.limit >= limits[i]] = 1
    percent.len.limit[percent.len.limit < limits[i]] = 0

    #For each exon calculate number of individuals with >= 75% of exon
    col <- colSums(percent.len.limit != 0)

    #Calculate % individuals with >= 75% of exon for each exon
    col <-
      col / (length(percent.len.limit[, 1]))

    exon_stats[i, j] <-  table(col >= limits[j])[2]

  }

}

exon_stats

#make table presentable
colnames(exon_stats) <-
  c("25% inds", "50% inds", "75% inds", "90% inds")
rownames(exon_stats) <-
  c("25% exons", "50% exons", "75% exons", "90% exons")
exon_stats[is.na(exon_stats)] <- 0
write.csv(exon_stats, "outputs/myristicaceae_exon_filtering_stats.csv")
