####
#all
####

#Here, set the file name of the table generated by get_seq_lengths.py
sample.filename = "data/test_seq_lengths.txt"

#use their script to import to ensure correct ref lengths
sample.data= as.matrix(read.table(sample.filename,header=T,row.names=1,sep="\t"))

#set length of reference exon
reference.len = as.numeric(sample.data[1,])

#extract only sample exon lengths
sample.len = sample.data[2:length(sample.data[,1]),]

#calculate percentage of exon recovered for each exon in each individual
percent.len= sweep(sample.len, 2, reference.len, "/")
percent.len = ifelse(percent.len>1,1,percent.len)
percent.len.0.75 <- percent.len

# if percentage exon length recovered is >= 75% make value 1
# if not make value 0
percent.len.0.75[percent.len.0.75>=0.75] = 1
percent.len.0.75[percent.len.0.75<0.75] = 0

#For each exon calculate number of individuals with >= 75% of exon
col <- colSums(percent.len.0.75 != 0)

#Calculate % individuals with >= 75% of exon for each exon
col <- col / (length(sample.data[,1])-1) # -1 for meanlength
table(col>=0.50)

#Extract only 75_75 exons from original dataset
length7575<-sample.data[,col>=0.50]

#Density plot of exon lengths with rug of actual exon lengths

#make data frame
marker_len<-data.frame(names(length7575[1,]),as.numeric(length7575[1,]))
colnames(marker_len)<-c("locus","length")

#remove X from locus name
marker_len$locus<-gsub("X","",marker_len$locus)

#
library(ggpubr)
# Basic density plot with mean line and marginal rug
ggdensity(marker_len, x = "length",
          fill = "#0073C2FF", color = "#0073C2FF", alpha=0.25,
          add = "mean", rug = TRUE)

#Copy list of names into a file, and modify to the format shown in README
cat(x = paste0("cp *", marker_len$locus, "_supercontig.FNA* 75_75/"), file = "outputs/75_75.txt", sep = "\n")
