rm(list=ls())

####
#all
####

library(ggpubr)
library(tidyverse)

#Here, set the file name of the table generated by get_seq_lengths.py
sample.filename = "data/test_seq_lengths.txt"

#use their script to import to ensure correct ref lengths
sample.data = as.matrix(read.table(
  sample.filename,
  header = T,
  row.names = 1,
  sep = "\t"
))

#remove X from locus name
colnames(sample.data) <- gsub("X", "", colnames(sample.data))

#view data
#view(sample.data)

#set length of reference exon
reference.len = as.numeric(sample.data[1,])

#extract only sample exon lengths
sample.len = sample.data[2:length(sample.data[, 1]),]

#calculate percentage of exon recovered for each exon in each individual
percent.len = sweep(sample.len, 2, reference.len, "/")
percent.len = ifelse(percent.len > 1, 1, percent.len)

####
#uncomment to ID low data samples
####
percent.len.low = ifelse(percent.len > 0.01, 1, percent.len)
percent.len.low_df<-data.frame(sort(rowSums(percent.len.low)))
#view(percent.len.low_df)

###
# taxonomic scale
###

#set scale
ts<-"asd"

#read in taxonomy dataset
tn<-read.csv("data/sample_data - samples_for_phylo.csv")

#only those samples output put hybpiper
tn<-tn[tn$included_hybpiper==1,]

#check for differences
setdiff(tn$Namelist,rownames(percent.len))
setdiff(rownames(percent.len),tn$Namelist)

filename<-"figures/fig3_heatmap.png"

#set thresholds
#limits <- c(0.25, 0.5, 0.75, 0.9)
limits <- seq(0.01, 0.99, 0.01)
limits

#make empty matrix
exon_stats <- matrix(nrow = length(limits), ncol = length(limits))

#loop through threshold combinations
for (i in 1:length(limits)) {
  for (j in 1:length(limits)) {

    #reset limits
    percent.len.limit <- percent.len

    # if percentage exon length recovered is >= 75% make value 1
    # if not make value 0
    percent.len.limit[percent.len.limit >= limits[i]] = 1
    percent.len.limit[percent.len.limit < limits[i]] = 0

    #For each exon calculate number of individuals with >= 75% of exon
    col <- colSums(percent.len.limit != 0)

    #Calculate % individuals with >= 75% of exon for each exon
    col <- col / (length(percent.len[, 1])) # -1 for meanlength

    exon_stats[i, j] <-  table(col >= limits[j])["TRUE"]

    print(paste("% exon",i, "% inds",j,sep=" "))

  }

}

#####
# ---- Figure 3 Heatmap ----
#####

#convert to data frame
#Rows are exon length
#Columns are individual proportion
exon_stats <- data.frame(exon_stats)

#view table
View(exon_stats)

#rename columns based on limits
for (i in 1:length(limits)) {
  colnames(exon_stats)[i] <-  limits[i] * 100
  exon_stats$exon_prop[i] <-  limits[i] * 100 #add column to represent exon proportion for melting
}

#melt table
library(reshape2)
exon_stats_melt <- melt(exon_stats, id.vars = "exon_prop")
head(exon_stats_melt)
exon_stats_melt$variable <- as.numeric(exon_stats_melt$variable)
colnames(exon_stats_melt) <- c("exon_prop", "ind_prop", "no_markers")
str(exon_stats_melt)

#covert NA to 0
#exon_stats_melt[is.na(exon_stats_melt)]<-0

#points for annotation
x<-c(10,25,50,75,25,75)
y<-c(10,25,50,75,75,25)
ast_filt<-data.frame(x,y)
ast_filt

#get number of markers for annotation
no_markers <- as.character(c(exon_stats[10, 10],
                             exon_stats[25, 25],
                             exon_stats[50, 50],
                             exon_stats[75, 75],
                             exon_stats[25, 75],
                             exon_stats[75, 25]))


#colors
library(wesanderson)

# Gradient color
pal <- wes_palette("Zissou1", 100, type = "continuous")
p <- ggplot(exon_stats_melt, aes(exon_prop, ind_prop, z = no_markers))
p2 <- p + geom_raster(aes(fill = no_markers)) +
  scale_fill_gradientn(colours = pal, name = "No. exons") +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
  labs(y= "i = % samples with exon", x = "l = % exon length recovered") +
  geom_contour(colour = "white", linetype = "dashed", alpha = 0.5) +
  theme(
    text = element_text(size = 10),
    axis.text = element_text(size = 10),
    axis.title.x = element_text(size = 11, margin = margin(
      t = 5,
      r = 0,
      b = 0,
      l = 0
    )),
    #axis.text.x=element_blank(),
    #axis.ticks.x=element_blank(),
    #axis.line.x = element_line(),
    #axis.title.y = element_blank(),
    #axis.text.y = element_blank(),
    #axis.ticks.y = element_blank(),
    #axis.line.y = element_blank(),
    legend.key = element_blank(),
    legend.title = element_text(),
    legend.text = element_text(size = 10),
    #legend.position = c(0.8, 0.9),
    panel.border = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    panel.background = element_blank())

p2 +
  annotate("point", x = ast_filt$x, y = ast_filt$y, size=2, alpha=0.7, pch=3, stroke=1) +
  annotate("text", x = ast_filt$x+2.5, y = ast_filt$y+2.5, label = no_markers, size=3, alpha=0.7)

ggsave(filename,  width = 17.5,
       height = 15,
       units = "cm")
