rm(list=ls())

####
#all
####

library(ggpubr)
library(tidyverse)
library(tictoc)

#Here, set the file name of the table generated by get_seq_lengths.py
sample.filename = "data/test_seq_lengths.txt"

#use their script to import to ensure correct ref lengths
sample.data = as.matrix(read.table(
  sample.filename,
  header = T,
  row.names = 1,
  sep = "\t"
))

#remove X from locus name
colnames(sample.data) <- gsub("X", "", colnames(sample.data))

#view data
#view(sample.data)

#set length of reference exon
reference.len = as.numeric(sample.data[1,])

#extract only sample exon lengths
sample.len = sample.data[2:length(sample.data[, 1]),]

#calculate percentage of exon recovered for each exon in each individual
percent.len = sweep(sample.len, 2, reference.len, "/")
percent.len = ifelse(percent.len > 1, 1, percent.len)

###
# taxonomic scale
###

#read in taxonomy dataset
tn<-read.csv("data/taxonomy_namelist.csv")

#only those samples output put hybpiper
tn<-tn[tn$Include_hybpiper==1,]

#check for differences
setdiff(tn$Namelist,rownames(percent.len))
setdiff(rownames(percent.len),tn$Namelist)

####
#uncomment for GENUS
####

percent.len<-cbind.data.frame(percent.len,tn$Genus)
percent.len<-aggregate(percent.len, by = list(percent.len[,length(percent.len[1,])]), max)
rownames(percent.len)<-percent.len[,1]
percent.len<-percent.len[,2:(length(percent.len[1,])-1)]
percent.len<-as.matrix(percent.len)

####
#uncomment for FAMILY
####

#percent.len<-cbind.data.frame(percent.len,tn$Family)
#percent.len<-aggregate(percent.len, by = list(percent.len[,length(percent.len[1,])]), max)
#rownames(percent.len)<-percent.len[,1]
#percent.len<-percent.len[,2:(length(percent.len[1,])-1)]
#percent.len<-as.matrix(percent.len)

#set thresholds
#limits <- c(0.25, 0.5, 0.75, 0.9)
limits <- seq(0.01, 0.99, 0.01)
limits

#make empty matrix
exon_stats <- matrix(nrow = length(limits), ncol = length(limits))

#loop through threshold combinations
for (i in 1:length(limits)) {
  for (j in 1:length(limits)) {

    #reset limits
    percent.len.limit <- percent.len

    # if percentage exon length recovered is >= 75% make value 1
    # if not make value 0
    percent.len.limit[percent.len.limit >= limits[i]] = 1
    percent.len.limit[percent.len.limit < limits[i]] = 0

    #For each exon calculate number of individuals with >= 75% of exon
    col <- colSums(percent.len.limit != 0)

    #Calculate % individuals with >= 75% of exon for each exon
    col <- col / (length(percent.len[, 1])) # -1 for meanlength

    exon_stats[i, j] <-  table(col >= limits[j])["TRUE"]

    print(paste("% exon",i, "% inds",j,sep=" "))

  }

}

#####
# Gradient plot
#####

#convert to data frame
exon_stats <- data.frame(exon_stats)

#view table
#view(exon_stats)

for (i in 1:length(limits)) {
  colnames(exon_stats)[i] <-  limits[i] * 100
  exon_stats$exon_prop[i] <-  limits[i] * 100
}


#melt table
library(reshape2)
exon_stats_melt <- melt(exon_stats, id.vars = "exon_prop")
head(exon_stats_melt)
exon_stats_melt$variable <- as.numeric(exon_stats_melt$variable)
colnames(exon_stats_melt) <- c("exon_prop", "ind_prop", "no_markers")
str(exon_stats_melt)

#covert NA to 0
#exon_stats_melt[is.na(exon_stats_melt)]<-0
library(wesanderson)

# Gradient color
pal <- wes_palette("Zissou1", 100, type = "continuous")
p <- ggplot(exon_stats_melt, aes(exon_prop, ind_prop, z = no_markers))
p + geom_raster(aes(fill = no_markers)) +
  scale_fill_gradientn(colours = pal, name = "No. exons") +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
  labs(y= "% families with exon", x = "% exon length recovered") +
  geom_contour(colour = "white", linetype = "dashed", alpha = 0.5) +
  theme(
    text = element_text(size = 10),
    axis.text = element_text(size = 10),
    axis.title.x = element_text(size = 11, margin = margin(
      t = 5,
      r = 0,
      b = 0,
      l = 0
    )),
    #axis.text.x=element_blank(),
    #axis.ticks.x=element_blank(),
    #axis.line.x = element_line(),
    #axis.title.y = element_blank(),
    #axis.text.y = element_blank(),
    #axis.ticks.y = element_blank(),
    #axis.line.y = element_blank(),
    legend.key = element_blank(),
    legend.title = element_text(),
    legend.text = element_text(size = 10),
    #legend.position = c(0.8, 0.9),
    panel.border = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    panel.background = element_blank()
  )

ggsave("figures/exon_recovery_gradient_family.png")

####
# Save table
####

#set thresholds
limits <- c(0.25, 0.5, 0.75, 0.9)
#limits <- seq(0.01,0.99,0.01)
limits

#make empty matrix
exon_stats <- matrix(nrow = length(limits), ncol = length(limits))

#loop through threshold combinations
for (i in 1:length(limits)) {
  for (j in 1:length(limits)) {
    percent.len.limit <- percent.len

    # if percentage exon length recovered is >= 75% make value 1
    # if not make value 0
    percent.len.limit[percent.len.limit >= limits[i]] = 1
    percent.len.limit[percent.len.limit < limits[i]] = 0

    #For each exon calculate number of individuals with >= 75% of exon
    col <- colSums(percent.len.limit != 0)

    #Calculate % individuals with >= 75% of exon for each exon
    col <-
      col / (length(sample.data[, 1]) - 1) # -1 for meanlength

    exon_stats[i, j] <-  table(col >= limits[j])[2]

  }

}

#make table presentable
colnames(exon_stats) <-
  c("25% inds", "50% inds", "75% inds", "90% inds")
rownames(exon_stats) <-
  c("25% exons", "50% exons", "75% exons", "90% exons")
exon_stats[is.na(exon_stats)] <- 0
write.csv(exon_stats, "outputs/exon_filtering_stats.csv")

# if percentage exon length recovered is >= 75% make value 1
# if not make value 0
percent.len.limit <- percent.len
percent.len.limit[percent.len.limit >= 0.50] = 1
percent.len.limit[percent.len.limit < 0.50] = 0

#For each exon calculate number of individuals with >= 75% of exon
col <- colSums(percent.len.limit != 0)

#Calculate % individuals with >= 75% of exon for each exon
col <- col / (length(sample.data[, 1]) - 1) # -1 for meanlength
table(col >= 0.50)

#Extract only 75_75 exons from original dataset
length7575 <- sample.data[, col >= 0.50]

#Density plot of exon lengths with rug of actual exon lengths
#make data frame
marker_len <-
  data.frame(names(length7575[1,]), as.numeric(length7575[1,]))
colnames(marker_len) <- c("locus", "length")

# Basic density plot with mean line and marginal rug
ggdensity(
  marker_len,
  x = "length",
  fill = "#0073C2FF",
  color = "#0073C2FF",
  alpha = 0.15,
  add = "mean",
  rug = TRUE,
  xlab = "Recovered exon length (bp)",
  ylab = "Density"
)

ggsave("figures/exon_length_density.png")

#Copy list of names into a file, and modify to the format shown in README
cat(
  x = paste0("cp *", marker_len$locus, "_supercontig.FNA* 50_50/"),
  file = "outputs/50_50.txt",
  sep = "\n"
)
