rm(list=ls())

####
#all
####

library(ggpubr)
library(tidyverse)

#Here, set the file name of the table generated by get_seq_lengths.py
sample.filename = "data/test_seq_lengths.txt"

#use their script to import to ensure correct ref lengths
sample.data = as.matrix(read.table(
  sample.filename,
  header = T,
  row.names = 1,
  sep = "\t"
))

#remove X from locus name
colnames(sample.data) <- gsub("X", "", colnames(sample.data))

#view data
#view(sample.data)

#set length of reference exon
reference.len = as.numeric(sample.data[1,])

#extract only sample exon lengths
sample.len = sample.data[2:length(sample.data[, 1]),]

#calculate percentage of exon recovered for each exon in each individual
percent.len = sweep(sample.len, 2, reference.len, "/")
percent.len = ifelse(percent.len > 1, 1, percent.len)

####
#uncomment to ID low data samples
####
percent.len.low = ifelse(percent.len > 0.01, 1, percent.len)
percent.len.low_df<-data.frame(sort(rowSums(percent.len.low)))
view(percent.len.low_df)

###
# taxonomic scale
###

#read in taxonomy dataset
tn<-read.csv("data/taxonomy_namelist.csv")

#only those samples output put hybpiper
tn<-tn[tn$Include_hybpiper==1,]

#check for differences
setdiff(tn$Namelist,rownames(percent.len))
setdiff(rownames(percent.len),tn$Namelist)

#set thresholds
limits <- c(0.25, 0.5, 0.75, 0.9)

#make empty matrix
exon_stats <- matrix(nrow = length(limits), ncol = length(limits))

#loop through threshold combinations
for (i in 1:length(limits)) {
  for (j in 1:length(limits)) {
    percent.len.limit <- percent.len

    # if percentage exon length recovered is >= 75% make value 1
    # if not make value 0
    percent.len.limit[percent.len.limit >= limits[i]] = 1
    percent.len.limit[percent.len.limit < limits[i]] = 0

    #For each exon calculate number of individuals with >= 75% of exon
    col <- colSums(percent.len.limit != 0)

    #Calculate % individuals with >= 75% of exon for each exon
    col <-
      col / (length(sample.data[, 1]) - 1) # -1 for meanlength

    exon_stats[i, j] <-  table(col >= limits[j])[2]

  }

}

#make table presentable
colnames(exon_stats) <-
  c("25% inds", "50% inds", "75% inds", "90% inds")
rownames(exon_stats) <-
  c("25% exons", "50% exons", "75% exons", "90% exons")
exon_stats[is.na(exon_stats)] <- 0
write.csv(exon_stats, "outputs/exon_filtering_stats.csv")

# if percentage exon length recovered is >= 75% make value 1
# if not make value 0
percent.len.limit <- percent.len
percent.len.limit[percent.len.limit >= 0.5] = 1
percent.len.limit[percent.len.limit < 0.5] = 0

#For each exon calculate number of individuals with >= 75% of exon
col <- colSums(percent.len.limit != 0)

#Calculate % individuals with >= 75% of exon for each exon
col <- col / (length(sample.data[, 1]) - 1) # -1 for meanlength

#Extract only 75_75 exons from original dataset
length7575 <- sample.data[, col >= 0.5]

#Density plot of exon lengths with rug of actual exon lengths
#make data frame
marker_len <-
  data.frame(names(length7575[1,]), as.numeric(length7575[1,]))
colnames(marker_len) <- c("locus", "length")

# Basic density plot with mean line and marginal rug
ggdensity(
  marker_len,
  x = "length",
  fill = "#0073C2FF",
  color = "#0073C2FF",
  alpha = 0.15,
  add = "mean",
  rug = TRUE,
  xlab = "Recovered exon length (bp)",
  ylab = "Density"
)

ggsave("figures/exon_length_density.png")

#Copy list of names into a file, and modify to the format shown in README
cat(
  x = paste0("cp *", marker_len$locus, "_supercontig.FNA* filtered/"),
  file = "outputs/cp_filtered.txt",
  sep = "\n"
)
