
###
# ASTRAL tree with hybpiper locus recovery
###

rm(list = ls())

library(ape)
library(tidyr)

#read in tree and tips
phy <- read.tree("data/trees/astral_r10_l0_i0/astral_bs10_LPP.tre")
df <- read.csv("data/sample_data - samples_for_phylo_OM.csv")
df <- df[df$Namelist %in% phy$tip.label,]

#fix terminal branches
phy$edge.length[phy$edge.length == "NaN"] <- 0.25

#plot tree QS
phy <- ape::root(phy, "P0109B", edgelabel = T)
phy <- ladderize(phy)

library(ggplot2)
library(ggtree)

#Hybpiper recovery dataset
#Here, set the file name of the table generated by get_seq_lengths.py
sample.filename = "data/test_seq_lengths.txt"

#use their script to import to ensure correct ref lengths
sample.data = as.matrix(read.table(
  sample.filename,
  header = T,
  row.names = 1,
  sep = "\t"
))

#remove X from locus name
colnames(sample.data) <- gsub("X", "", colnames(sample.data))

#set length of reference exon
reference.len = as.numeric(sample.data[1, ])

#extract only sample exon lengths
sample.len = sample.data[2:length(sample.data[, 1]), ]

#calculate percentage of exon recovered for each exon in each individual
percent.len = sweep(sample.len, 2, reference.len, "/")
percent.len = ifelse(percent.len > 1, 1, percent.len)

#drop 1kp
phy <- drop.tip(phy, setdiff(phy$tip.label, rownames(percent.len)))

#check diffs
setdiff(phy$tip.label, rownames(percent.len))
setdiff(rownames(percent.len), phy$tip.label)

#remove those in hybpiper but not in tree from table
percent.len<-percent.len[match(phy$tip.label, rownames(percent.len)),]

#check diffs
setdiff(phy$tip.label, rownames(percent.len))
setdiff(phy$tip.label, rownames(percent.len))

#melt table
library(reshape2)
percent.len_melt <- melt(percent.len)
head(percent.len_melt)
colnames(percent.len_melt) <- c("label", "category", "value")

percent.len_melt$label <- as.character(percent.len_melt$label)
percent.len_melt$category <- as.character(percent.len_melt$category)
head(percent.len_melt)
str(percent.len_melt)

##
# COLOUR BASED ON ORDER
##

df2<-df[df$Namelist%in%phy$tip.label,]
df2

df2<-df2[match(phy$tip.label, df2$Namelist),]

df3<-data.frame(phy$tip.label, df2$Order)
colnames(df3)<-c("label","order")
head(df3)



#check diffs
setdiff(phy$tip.label, df3$label)
setdiff(df3$label, phy$tip.label)



#tree

g <- ggtree(phy)


g2 <- g %<+% df3 +
  geom_tiplab(aes(color = factor(order)),align = T, size = 1.75) + theme(legend.position = c(0.1,0.9),
                                                                         legend.title = element_blank(), # no title
                                                                         #legend.key = element_blank(),
                                                                         legend.text = element_text(size= 7)
  ) + guides(colour = guide_legend(override.aes = list(size=5)))


g2

#table

#CHECK IF THE DATA IS IN CORRECT ORDER
p2 <- ggplot(percent.len_melt, aes(x = category, y = label)) +
  geom_tile(aes(fill = value)) + scale_fill_viridis_c(name="% exon length") +
  theme_tree2() + theme(
    axis.line.x = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    #legend.title =element_blank(),
    legend.text = element_text(size = 7.5),
    legend.margin = margin(0, 0, 0, 0, "cm")
    #legend.position = "none"
  )

p2

pdf('figures/tree_exon_recovery.pdf', height=20,width=20)
library(aplot)
p2 %>% insert_left(g2)
dev.off()
