

###
# ASTRAL
###

par(mar = c(0, 0, 0, 0))

library(ape)
library(phylotools)
library(RColorBrewer)
library(tidyr)

palette(colorRampPalette(brewer.pal(name = "Set1", n = 8))(17))

#read in tree and tips
phy <- read.tree("data/trees/astral_all_bs10_lpp.tre")
df <- read.csv("data/taxonomy_namelist.csv")
df <- df[df$Namelist %in% phy$tip.label,]
df <-
  df %>% unite("genus_species",
               Genus:Species,
               na.rm = TRUE,
               remove = FALSE)

##tip label change
dfnames <- data.frame(df$Namelist, df$genus_species)
phy <- sub.taxa.label(phy, dfnames)
phy$edge.length[phy$edge.length == "NaN"] <- 0.25

#cols
df <- df[match(phy$tip.label, df$genus_species),]

#plot tree QS
phy <- root(phy, "Chloranthus_spicatus", edgelabel = T)
phy <- ladderize(phy)
plot(
  phy,
  cex = 0.5,
  label.offset = 0.05,
  align.tip.label = T,
  edge.width = 2,
  edge.color = "grey",
  tip.color = as.numeric(as.factor(df$Order))
)
p <- character(length(phy$node.label))

phy <- read.tree("data/trees/astral_all_bs10_QS.tre")
nodelabels(
  pie = cbind(as.numeric(phy$node.label), 100 - as.numeric(phy$node.label)),
  piecol = c("grey", "white"),
  cex = 0.25
)

phy <- read.tree("data/trees/astral_all_bs10_LPP.tre")
nodelabels(
  pie = cbind(as.numeric(phy$node.label), 1 - as.numeric(phy$node.label)),
  piecol = c("black", "white"),
  cex = 0.125
)

legend(
  'bottomleft',
  legend = c(
    'canellales',
    'chloranthales',
    'laurales',
    'magnoliales',
    'piperales',
    'Local PP',
    'Quartet support'
  ),
  text.col = c(1, 2, 3, 4, 5, "black", "black"),
  pt.cex = c(NA, NA, NA, NA, NA, 2, 2),
  pch = c(NA, NA, NA, NA, NA, 16, 16),
  col = c(NA, NA, NA, NA, NA, "black", "grey"),
  bty = 'n'
)

###
# Coverage data
###

x <- read.tree("data/trees/astral_50_50/astral_all_bs10_LPP.tre")
info <- read.csv("data/test_seq_lengths.txt")

p <- ggtree(x) %<+% info + xlim(-.1, 4)
p2 <- p + geom_tiplab(offset = .6, hjust = .5) +
  geom_tippoint(aes(
    shape = trophic_habit,
    color = trophic_habit,
    size = mass_in_kg
  )) +
  theme(legend.position = "right") + scale_size_continuous(range = c(3, 10))

## d2 <- read.csv(paste0(url, "inode_data.csv"))
d2 <- read.csv("data/inode_data.csv")
p2 %<+% d2 + geom_label(aes(label = vernacularName.y, fill = posterior)) +
  scale_fill_gradientn(colors = RColorBrewer::brewer.pal(3, "YlGnBu"))

####
# IQTREE
####

phy <-
  read.tree("~/Dropbox/projects/TC_raphia/iqtree/raphia.partitions.contree")
df <- read.csv("tip_names.csv")
df <- df[df$old %in% phy$tip.label, ]
dfnames <- data.frame(df$old, df$new)
dfnames <- dfnames[phy$tip.label %in% dfnames$df.old, ]
phy <- sub.taxa.label(phy, dfnames)
plot(phy)
nodelabels()

phy <- root(phy, node = 110)
phy <- ladderize(phy)
plot(phy, cex = 0.7, label.offset = 0.001)

iqphy <-
  drop.tip(
    phy,
    c(
      "Mauritiella_armata_R37_T6",
      "Laccosperma_cristalensis_R41_T41",
      "Eremospatha_cabrae_R67_T28",
      "Eremospatha_quiquecostulata_R41_T39"
    )
  )

jpeg(
  "iqtree_raphia.jpg",
  width = 2500,
  height = 2500,
  res = 300
)
plot(iqphy, cex = 0.7, label.offset = 0.001)
p <- character(length(iqphy$node.label))
nodelabels(
  pie = cbind(
    as.numeric(iqphy$node.label),
    100 - as.numeric(iqphy$node.label)
  ),
  piecol = c("black", "white"),
  cex = 0.3
)
dev.off()

###
# With hybpiper locus recovery
###

rm(list = ls())

library(ape)
library(tidyr)

#read in tree and tips
phy <- read.tree("data/trees/astral_50_50/astral_all_bs10_LPP.tre")
df <- read.csv("data/taxonomy_namelist.csv")
df <- df[df$Namelist %in% phy$tip.label,]
df <-
  df %>% tidyr::unite("genus_species",
                      Genus:Species,
                      na.rm = TRUE,
                      remove = FALSE)

##tip label change
#dfnames <- data.frame(df$Namelist, df$genus_species)
#phy <- phylotools::sub.taxa.label(phy, dfnames)
phy$edge.length[phy$edge.length == "NaN"] <- 0.25

#plot tree QS
phy <- ape::root(phy, "P0109B", edgelabel = T)
phy <- ladderize(phy)

library(ggplot2)
library(ggtree)

#Hybpiper recovery dataset
#Here, set the file name of the table generated by get_seq_lengths.py
sample.filename = "data/test_seq_lengths.txt"

#use their script to import to ensure correct ref lengths
sample.data = as.matrix(read.table(
  sample.filename,
  header = T,
  row.names = 1,
  sep = "\t"
))

#remove X from locus name
colnames(sample.data) <- gsub("X", "", colnames(sample.data))

#set length of reference exon
reference.len = as.numeric(sample.data[1, ])

#extract only sample exon lengths
sample.len = sample.data[2:length(sample.data[, 1]), ]

#calculate percentage of exon recovered for each exon in each individual
percent.len = sweep(sample.len, 2, reference.len, "/")
percent.len = ifelse(percent.len > 1, 1, percent.len)

#drop 1kp
phy <- drop.tip(phy, setdiff(phy$tip.label, rownames(percent.len)))

#check diffs
setdiff(phy$tip.label, rownames(percent.len))
setdiff(rownames(percent.len), phy$tip.label)

percent.lens<-percent.len[match(phy$tip.label, rownames(percent.len)),]

#melt table
library(reshape2)
percent.len_melt <- melt(percent.len)
head(percent.len_melt)
colnames(percent.len_melt) <- c("label", "category", "value")

percent.len_melt$label <- as.character(percent.len_melt$label)
percent.len_melt$category <- as.character(percent.len_melt$category)
head(percent.len_melt)
str(percent.len_melt)

##
# COLOUR BASED ON ORDER
##

df2<-df[df$Namelist%in%phy$tip.label,]
df2

df2<-df2[match(phy$tip.label, df2$Namelist),]

df3<-data.frame(phy$tip.label, df2$Order)
colnames(df3)<-c("label","order")
head(df3)



#check diffs
setdiff(phy$tip.label, df3$label)
setdiff(df3$label, phy$tip.label)



#tree

g <- ggtree(phy)


g2 <- g %<+% df3 +
  geom_tiplab(aes(color = factor(order)),align = T, size = 1.75) + theme(legend.position = c(0.1,0.9),
        legend.title = element_blank(), # no title
        #legend.key = element_blank(),
        legend.text = element_text(size= 7)
        ) + guides(colour = guide_legend(override.aes = list(size=5)))


g2

#table

#CHECK IF THE DATA IS IN CORRECT ORDER
p2 <- ggplot(percent.len_melt, aes(x = category, y = label)) +
  geom_tile(aes(fill = value)) + scale_fill_viridis_c(name="% exon length") +
  theme_tree2() + theme(
    axis.line.x = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    #legend.title =element_blank(),
    legend.text = element_text(size = 7.5),
    legend.margin = margin(0, 0, 0, 0, "cm")
    #legend.position = "none"
  )

p2

pdf('figures/tree_exon_recovery.pdf', height=20,width=20)
library(aplot)
p2 %>% insert_left(g2)
dev.off()

